/// "DO NOT PUT YOUR GOOGLE MAPS API KEY IN A PRODUCTION APP.
/// DON'T DISTRIBUTE IT.
/// WHEN YOU'RE DOING QUICK DEMOS ON-SCREEN, THAT'S OKAY;
/// BUT DON'T DO IT WITH PRODUCTION.
/// JUST SAYIN'
const googleMapsApiKey = '[YOUR API KEY HERE]';
